Repository cypress-io/cypress-docker-images, pull requests merged in 2024-07, with the labels that each got.

#1135 docs: fix README formatting
  README.md
Labels: documentation 📝

#1140 build: use uppercase FROM / AS combination in Dockerfile
  factory/Dockerfile
  factory/factory.Dockerfile
Labels: bug, topic: build process

#1148 ci: remove workflow version from circle.yml
  circle.yml
Labels: bug, topic: build process

#1149 ci: remove unused node orb from circle.yml
  circle.yml
Labels: topic: build process

#1150 ci: correct circle.yml indentation syntax error
  circle.yml
Labels: bug, topic: build process

#1151 ci: check image exists with Docker Hub API
  circle.yml
Labels: type: enhancement, topic: build process

#1152 build: disable default provenance attestation
  circle.yml
Labels: type: enhancement, topic: build process

#1147 chore: update circleci to ubuntu-2204:2023.04.2 machine image
  circle.yml
Labels: type: enhancement, topic: build process

#1138 fix: update cypress/factory to Debian 12.6
  factory/.env
  factory/CHANGELOG.md
Labels: type: enhancement

#1154 chore(deps): update to Node.js 20.15.1
  factory/.env
  factory/CHANGELOG.md
Labels: bug, type: enhancement

#1155 chore: update circleci to ubuntu-2204:2023.10.1 machine image
  circle.yml
Labels: type: enhancement, topic: build process

#1157 docs: fix CHANGELOG formatting
  factory/CHANGELOG.md
Labels: type: enhancement, documentation 📝

#1158 chore(deps): update Firefox to 128
  factory/.env
Labels: type: enhancement

#1159 build: add version information to logs
  circle.yml
Labels: type: enhancement, topic: build process

#1160 chore: update circleci to ubuntu-2204:2024.01.1 machine image
  circle.yml
Labels: type: enhancement

#1161 docs: add entrypoint info to included README
  included/README.md
Labels: type: enhancement, documentation 📝

#1162 ci: fix compose --progress plain build cli syntax
  circle.yml
Labels: bug, topic: build process

#1164 docs: add security policy
  SECURITY.md
Labels: type: enhancement, documentation 📝

#1165 test: bump args-defined browser versions
  factory/test-project/argsDefined.Dockerfile
  factory/test-project/docker-compose.yml
Labels: bug

#1169 docs: add user parameter info to main readme
  README.md
Labels: type: enhancement, documentation 📝

#1170 docs: link into docs CI examples
  README.md
Labels: type: enhancement, documentation 📝

#1163 chore: update circleci to ubuntu-2204:2024.05.1 (latest) machine image
  circle.yml
Labels: type: enhancement

#1172 docs: re-format contributing
  CONTRIBUTING.md
Labels: documentation 📝

#1174 docs: re-format internal readme files
  base-internal/README.md
  base-internal/releases/node-18/18.15.0/README.md
  base-internal/releases/node-18/18.16.0/README.md
  base-internal/releases/node-18/18.17.0/README.md
  base-internal/releases/node-18/18.17.1/README.md
  base-internal/releases/node-18/18.18.2/README.md
  base-internal/releases/node-18/18.20.2/README.md
  base-internal/releases/node-20/20.15.0/README.md
  base-internal/releases/ubuntu/ubuntu20-node16/README.md
  base-internal/releases/ubuntu/ubuntu20-node18/README.md
  browsers-internal/README.md
  browsers-internal/releases/node-18/node18.15.0-chrome114-ff115-edge/README.md
  browsers-internal/releases/node-18/node18.15.0-chrome114-ff115/README.md
  browsers-internal/releases/node-18/node18.16.0-chrome116-ff115-edge/README.md
  browsers-internal/releases/node-18/node18.16.0-chrome116-ff115/README.md
  browsers-internal/releases/node-18/node18.17.0-chrome118-ff115-edge/README.md
  browsers-internal/releases/node-18/node18.17.0-chrome118-ff115/README.md
  browsers-internal/releases/node-18/node18.17.1-chrome118-ff115-edge/README.md
  browsers-internal/releases/node-18/node18.17.1-chrome118-ff115/README.md
  browsers-internal/releases/node-18/node18.17.1-chrome124-ff125-edge/README.md
  browsers-internal/releases/node-18/node18.17.1-chrome124-ff125/README.md
  browsers-internal/releases/node-18/node18.18.2-chrome120-ff115-edge/README.md
  browsers-internal/releases/node-18/node18.18.2-chrome120-ff115/README.md
  browsers-internal/releases/node-18/node18.18.2-chrome125-ff126-edge/README.md
  browsers-internal/releases/node-18/node18.18.2-chrome125-ff126/README.md
  browsers-internal/releases/node-18/node18.20.2-chrome124-ff125/README.md
  browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/README.md
Labels: documentation 📝

#1173 docs: minor re-format readme files
  base/README.md
  browsers/README.md
  factory/README.md
  included/README.md
Labels: documentation 📝

#1171 chore(deps): update prettier to 3.3.3
  package-lock.json
  package.json
Labels: type: enhancement

#1175 chore: remove unused find-ecr-image.sh script
  find-ecr-image.sh
Labels: minor

#1176 chore: re-format html sources
  examples/basic-mini/index.html
  examples/basic/index.html
  examples/included-as-non-root/src/index.html
Labels: example 💎

#1177 chore: remove factory/test-project from prettier checks
  .prettierignore
Labels: type: enhancement

#1179 chore(deps): update Chrome to 127.0.6533.72-1
  factory/.env
Labels: type: enhancement

#1182 chore: add cypress 13.13.2 to docker factory and bump shipped browsers
  factory/.env
  factory/CHANGELOG.md
Labels: type: enhancement
