Repository cypress-io/cypress-docker-images, pull requests merged in 2024-06, with the labels that each got.

#1089 chore: remove legacy included test
  included/test.sh
Labels: type: enhancement

#1091 docs: migrate examples to relative bind mounts
  included/README.md
Labels: type: enhancement, documentation 📝

#1052 chore: add 18.18.2 chrome 125 firefore 126 related browser images
  browsers-internal/node18.18.2-chrome125-ff126-edge/Dockerfile
  browsers-internal/node18.18.2-chrome125-ff126-edge/README.md
  browsers-internal/node18.18.2-chrome125-ff126-edge/build.sh
  browsers-internal/node18.18.2-chrome125-ff126-edge/global-profile.sh
  browsers-internal/node18.18.2-chrome125-ff126/Dockerfile
  browsers-internal/node18.18.2-chrome125-ff126/README.md
  browsers-internal/node18.18.2-chrome125-ff126/build.sh
  browsers-internal/node18.18.2-chrome125-ff126/global-profile.sh
Labels: type: enhancement

#1092 docs: fix restrict cpu example
  included/README.md
Labels: bug, documentation 📝

#1094 Revert "ci: update circleci runner (#1079)"
  circle.yml
Labels: bug

#1099 docs: remove outdated blank screen issue
  README.md
Labels: type: enhancement, documentation 📝

#1096 docs: add missing bind mounts
  included/README.md
Labels: bug, documentation 📝

#1098 feat: publish set of node.js 18.20.3 images
  circle.yml
  factory/.env
  factory/docker-compose.yml
Labels: type: enhancement

#1107 docs: update Docker apt-get best practice reference
  CONTRIBUTING.md
Labels: type: enhancement, documentation 📝

#1106 docs: add tag infos to readme files
  README.md
  base/README.md
  browsers/README.md
  factory/README.md
  included/README.md
Labels: type: enhancement, documentation 📝

#1110 docs: add cypress/base examples
  base/README.md
  examples/basic/Dockerfile.base
  examples/basic/README.md
  examples/basic/cypress.config.js
  examples/basic/cypress/e2e/spec.cy.js
  examples/basic/index.html
  examples/basic/package-lock.json
  examples/basic/package.json
Labels: type: enhancement, documentation 📝

#1112 docs: add note for publishing and cypress/factory
  CONTRIBUTING.md
Labels: type: enhancement, documentation 📝

#1113 docs: add cypress/browsers examples
  browsers/README.md
  examples/basic/Dockerfile.browsers
Labels: type: enhancement, documentation 📝

#1116 docs: align terms in factory readme
  factory/README.md
Labels: bug, documentation 📝

#1118 docs: add examples/basic-mini project - w/o Cypress version
  examples/basic-mini/README.md
  examples/basic-mini/cypress.config.js
  examples/basic-mini/cypress/e2e/spec.cy.js
  examples/basic-mini/index.html
  examples/basic-mini/package-lock.json
  examples/basic-mini/package.json
Labels: type: enhancement, documentation 📝

#1123 docs: add cypress github action examples
  .github/workflows/example-cypress-github-action.yml
  README.md
Labels: type: enhancement, documentation 📝, example 💎

#1124 docs: factory version bump description
  CONTRIBUTING.md
  factory/.env
Labels: documentation 📝

#1117 docs: add examples readme links to readme
  README.md
Labels: type: enhancement, documentation 📝

#1127 Migrate examples/included-as-non-root to Cypress 13.x
  examples/included-as-non-root/Dockerfile
  examples/included-as-non-root/README.md
  examples/included-as-non-root/build.sh
  examples/included-as-non-root/src/cypress.config.js
  examples/included-as-non-root/src/cypress.json
  examples/included-as-non-root/src/cypress/e2e/spec.cy.js
  examples/included-as-non-root/src/cypress/integration/spec.js
  examples/included-as-non-root/src/index.html
  examples/included-as-non-root/test.sh
  included/README.md
Labels: bug, documentation 📝

#1125 docs: remove non-working base-internal Dockerfile example
  base-internal/releases/node-18/18.15.0/README.md
  base-internal/releases/node-18/18.16.0/README.md
  base-internal/releases/node-18/18.17.0/README.md
  base-internal/releases/node-18/18.17.1/README.md
  base-internal/releases/node-18/18.18.2/README.md
  base-internal/releases/node-18/18.20.2/README.md
Labels: bug, documentation 📝

#1131 docs: add platform information
  README.md
  browsers/README.md
  included/README.md
Labels: type: enhancement, documentation 📝

#1128 Remove examples/included-as-non-root-alternative
  examples/included-as-non-root-alternative/Dockerfile
  examples/included-as-non-root-alternative/README.md
  examples/included-as-non-root-alternative/build.sh
  examples/included-as-non-root-alternative/src/cypress.json
  examples/included-as-non-root-alternative/src/cypress/integration/spec.js
  examples/included-as-non-root-alternative/src/index.html
  examples/included-as-non-root-alternative/test.sh
  included/README.md
Labels: bug, documentation 📝

#1133 chore: add 20.15.0 internal docker images
  base-internal/releases/node-20/20.15.0/Dockerfile
  base-internal/releases/node-20/20.15.0/README.md
  base-internal/releases/node-20/20.15.0/build.sh
  browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/Dockerfile
  browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/README.md
  browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/build.sh
  browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/global-profile.sh
Labels: type: enhancement
